### ISSUE TITLE
No module named 'llama_cpp'

### ISSUE THREAD

**Issue by theonetwoone** [ceruleandeep/ComfyUI-LLaVA-Captioner#1]
After installing and moving the models to the right folder I still get this when starting Comfyui:
```
Traceback (most recent call last):
  File "D:\AI-Programmer\ComfyUI\ComfyUI\nodes.py", line 1813, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI-Programmer\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LLaVA-Captioner\__init__.py", line 1, in <module>
    from .llava import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AI-Programmer\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LLaVA-Captioner\llava.py", line 12, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

Cannot import D:\AI-Programmer\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LLaVA-Captioner module for custom nodes: No module named 'llama_cpp'
```

**Comment by slavakurilyak** [comment]
I got the same `ModuleNotFoundError` which I resolved by installing `llama-cpp-python` inside `ComfyUI` folder.

Here's the fix:

```sh
cd ComfyUI
pip install llama-cpp-python
```

[llama-cpp-python](https://github.com/abetlen/llama-cpp-python) by @abetlen is a Python binding for [llama.cpp](https://github.com/ggerganov/llama.cpp) by @ggerganov.

**Comment by pixelass** [comment]
@slavakurilyak thanks for the tipp, but it didn't work for me. llama-cpp-python is installed now but can't be found. 
This repo needs a decent installation guide or better yet handle installs on its own.

**Comment by theonetwoone** [comment]
I found that it's likely a problem only for pre compiled comfyui users. Installing llamacpp manually then copy the dependencies from %appdata% local/programs/python/python310/lib/site-packages into the comfyui/python_embeded/lib/site-packages, fixes the the node works fine after

**Comment by pixelass** [comment]
I mean, yyeah one way to get rid of open issues is just closing them. 🤷 

@theonetwoone I appreciate your help but that does not work either.

> manually then copy the dependencies from

You must be kidding, right?

this will end in an endless manual moving of dependencies

```
ModuleNotFoundError: No module named 'diskcache'
```

**Comment by theonetwoone** [comment]
Sorry didn't mean to close it my bad!

**Comment by pixelass** [comment]
I got it to work by manually copying all dependencies (for me only 'diskcache' was remaining).
But something is still off, it takes 20s (so I gguess it's running on CPU).

This is a great tool if we put in some more work.

**Comment by AlexYez** [comment]
llama-cpp-python with GPU support:
CUDA 11.8
.\python_embeded\python.exe -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu118/

CUDA 12.2
.\python_embeded\python.exe -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122

**Comment by andreszs** [comment]
In my case the llama installation fails directly:

![image](https://github.com/ceruleandeep/ComfyUI-LLaVA-Captioner/assets/10298071/15d2d02b-acf1-485d-8d81-1d8b3ddf5eb6)

PS only now I see that to install that llama, VisualStudio is required.

**Comment by nguyenchiviet** [comment]
> llama-cpp-python with GPU support: CUDA 11.8 .\python_embeded\python.exe -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu118/
> 
> CUDA 12.2 .\python_embeded\python.exe -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu122

Thank you, AlexYez! Your solution worked perfectly! 🙌

I encountered an issue where ComfyUI was running Python 3.11.9 from its embedded folder D:\ComfyUI_windows_portable\python_embeded, but my system had Python 3.10.6 installed, and that version was prioritized in my system PATH. This caused conflicts when trying to install llama-cpp-python.

Here’s the detailed breakdown of what happened:

System Environment Conflict: My Windows 11 machine had the following directories at the top of my PATH:

C:\Python3106\Scripts\
C:\Python3106\
This caused the system to use Python 3.10.6 instead of the Python 3.11.9 that’s part of the embedded ComfyUI setup. Even though I ran commands from D:\ComfyUI_windows_portable\python_embeded, it still referenced the global Python version.

Solution:

I removed the above two entries from the PATH under System variables in the Environment Variables.
Afterward, I followed your command exactly:
bash
Copy code
.\python.exe -m pip install llama-cpp-python --prefer-binary --no-cache-dir --extra-index-url=https://jllllll.github.io/llama-cpp-python-cuBLAS-wheels/AVX2/cu121
(since I have CUDA 12.1)
Outcome: After running this, the installation succeeded, and everything worked smoothly. 🎉

For anyone encountering similar issues, make sure to check if your system’s PATH is prioritizing the wrong Python version. Removing conflicting entries and running the correct commands from the embedded Python environment fixed it for me.

Thanks again for your detailed help, and I hope this information can help others facing the same problem!
